### ISSUE TITLE
License is missing

### ISSUE THREAD

**Issue by mengelbrecht** [Geraet/Kompositum#1]
We should add a license. I am voting for MIT License.

**Comment by rehans** [comment]
Is MIT similar (or even the same) as Boost?

**Comment by mengelbrecht** [comment]
Similar but not the same. The Boost Software License does not require that the copyright notice is included in binaries whereas the MIT License does.

**Comment by rehans** [comment]
Ah ok. Please change the license appropriately within the files :)

**Comment by ghost** [comment]
How about updating the license file and don't repeat the license text in the headers?

**Comment by rehans** [comment]
Can you please give an example? I am not sure I got what you mean :) In the header files we put a link to the license file. There is only the copyright stuff with my name and this link.

**Comment by ghost** [comment]
I asking if we need to put this in each header file or just can use the license file. I am not a friend of repeating stuff.

**Comment by mengelbrecht** [comment]
We could do some research if the license notice is required in every source file. If not we could omit it.
