### ISSUE TITLE
Admin rights with an "Organization"

### ISSUE THREAD

**Issue by rehans** [Geraet/Kompositum#10]
In order to grant @mgee and @artopantone admin rights to Kompositum we need to create an "Organization". Any suggestions for a name?

**Comment by ghost** [comment]
Confidential Patterns ;)

**Comment by ghost** [comment]
'The Kompositum', or in german: "Der Kompositum", like "Der Gerät", you know! :+1:

**Comment by mengelbrecht** [comment]
What about `geraet` or `Geraet`?

**Comment by rehans** [comment]
Haha, "Geraet" is nice :D

**Comment by rehans** [comment]
"Geraet" is already taken :(((((

"DerGeraet" maybe?

**Comment by mengelbrecht** [comment]
Done.

**Comment by ghost** [comment]
hehe, nice! :+1:
